#!/bin/bash
# Complete iOS build on the Mac: Live Activity native parts + unsigned IPA including
# the embedded widget extension. Sign the result afterwards with Sideloadly
# (do NOT check "Remove App Extensions", otherwise the Live Activity gets stripped again).
set -euo pipefail
cd "$(dirname "$0")/.."

bash native/ios-liveactivity/build.sh

export PATH="$HOME/.dotnet:$PATH"
cd src/StudyLife.App
dotnet publish -f net10.0-ios -c Release -p:RuntimeIdentifier=ios-arm64 -p:EnableCodeSigning=false

IPA="bin/Release/net10.0-ios/ios-arm64/publish/StudyLife.App.ipa"

# Open the IPA for metadata injection; the widget extension is only added later in
# sign-and-install.sh (Xcode-built, see the comment there).
WORK=$(mktemp -d)
unzip -q "$IPA" -d "$WORK"

# Generate AppIntents metadata for the Live Activity's pause button: the runtime only
# finds intents via Payload/App.app/Metadata.appintents, which is normally written
# exclusively by Xcode during an app build - reproduced here via the const-value route
# (same approach as Bazel's rules_apple; const values come from native/ios-liveactivity/build.sh).
NATIVE_DIR="$(cd ../../native/ios-liveactivity && pwd)"
XCODE_BUILD_VERSION=$(xcodebuild -version | awk '/Build version/ {print $3}')
SFL=$(mktemp); printf '%s\n' \
    "$NATIVE_DIR/TimerActivityAttributes.swift" \
    "$NATIVE_DIR/TimerControlIntent.swift" \
    "$NATIVE_DIR/LiveActivityBridge.swift" > "$SFL"
SCV=$(mktemp); printf '%s\n' "$NATIVE_DIR/out/StudyLifeLiveActivity.swiftconstvalues" > "$SCV"
xcrun appintentsmetadataprocessor \
    --output "$WORK/Payload/StudyLife.App.app" \
    --toolchain-dir "$(dirname "$(dirname "$(dirname "$(xcrun --find swiftc)")")")" \
    --module-name StudyLifeLiveActivity \
    --sdk-root "$(xcrun --sdk iphoneos --show-sdk-path)" \
    --xcode-version "$XCODE_BUILD_VERSION" \
    --platform-family iOS \
    --deployment-target 16.2 \
    --target-triple arm64-apple-ios16.2 \
    --source-file-list "$SFL" \
    --swift-const-vals-list "$SCV" \
    --force --quiet-warnings
[ -d "$WORK/Payload/StudyLife.App.app/Metadata.appintents" ] \
    && echo "AppIntents metadata generated." \
    || echo "WARNING: Metadata.appintents missing - the pause button will not work"
rm -f "$SFL" "$SCV"

rm "$IPA"
(cd "$WORK" && zip -qry "$OLDPWD/$IPA" Payload)
rm -rf "$WORK"

# Keep the dSYM(s): dotnet publish's own output directory gets wiped/regenerated by the next
# build, so without this a MetricKit crash report (TelemetryBridge.swift, already-symbolicated
# where MetricKit provides it - see the README's "Telemetry (native)" section for the rest) has
# no matching debug symbols left to fully symbolicate with `atos` by the time it's actually
# looked at. Keyed by commit so a report can always be matched back to the exact build that
# produced it; gitignored (artifacts/) since these are build outputs, not source.
DSYM_VERSION="$(git -C "$OLDPWD" rev-parse --short HEAD 2>/dev/null || date +%Y%m%d%H%M%S)"
DSYM_OUT="$OLDPWD/artifacts/dsym/$DSYM_VERSION"
mkdir -p "$DSYM_OUT"
# dotnet publish leaves the dSYM next to the .app one level ABOVE publish/ (verified on the
# first phase-3 device build: bin/Release/net10.0-ios/ios-arm64/StudyLife.App.app.dSYM).
find bin/Release/net10.0-ios/ios-arm64 -maxdepth 2 -iname "*.dSYM" -exec cp -R {} "$DSYM_OUT/" \; 2>/dev/null || true
if [ -n "$(ls -A "$DSYM_OUT" 2>/dev/null)" ]; then
    echo "dSYM(s) kept: $DSYM_OUT"
else
    echo "WARNING: no dSYM found under the publish output - MetricKit crash frames may stay unsymbolicated"
fi

echo "IPA with Live Activity extension: src/StudyLife.App/$IPA"
