#!/bin/bash
# Builds the Live Activity native parts on the Mac (without an Xcode project, directly
# with swiftc):
#  1) libStudyLifeLiveActivity.a  - C ABI wrapper, gets linked into the .NET main app
#     (NativeReference in StudyLife.App.csproj, activates the LIVE_ACTIVITY define)
#  2) StudyLifeWidgets.appex      - widget extension with the lock screen UI,
#     gets embedded into the finished IPA by scripts/build-ios-ipa.sh
set -euo pipefail
cd "$(dirname "$0")"

SDK=$(xcrun --sdk iphoneos --show-sdk-path)
TARGET=arm64-apple-ios16.2
OUT=out
mkdir -p "$OUT"

echo "[1/2] Wrapper static library ..."
# -wmo + const-value emission: the basis for appintentsmetadataprocessor (Live Activity's
# pause button - AppIntents metadata is otherwise only generated by Xcode app builds,
# build-ios-ipa.sh reproduces this for the .NET app).
# Absolute source paths: appintentsmetadataprocessor matches the paths from the const
# values byte-for-byte against its --source-file-list - relative paths fail there.
swiftc -target "$TARGET" -sdk "$SDK" -O -parse-as-library -whole-module-optimization \
    -module-name StudyLifeLiveActivity \
    -emit-const-values-path "$OUT/StudyLifeLiveActivity.swiftconstvalues" \
    -Xfrontend -const-gather-protocols-file -Xfrontend "$PWD/ConstExtractProtocols.json" \
    -emit-library -static \
    -o "$OUT/libStudyLifeLiveActivity.a" \
    "$PWD/TimerActivityAttributes.swift" "$PWD/TimerControlIntent.swift" "$PWD/LiveActivityBridge.swift" \
    "$PWD/WatchBridge.swift" "$PWD/HealthBridge.swift" "$PWD/UpcomingSessionActivity.swift"

# The widget extension itself is NO LONGER built here: the swiftc hand-linked
# appex binary doesn't render on the device (Xcode's special linker setup is missing) -
# the production extension is built by xcodebuild via native/ios-signing (StudyLifeWidgetsShell),
# swapped in during scripts/sign-and-install.sh.
echo "Done: $OUT/libStudyLifeLiveActivity.a"
